-- V002__outbox_and_saga_state.sql
--
-- Flyway naming convention: V{version}__{description}.sql, same rule as
-- V001 — this file is checksummed into Flyway's history table on first run
-- and must never be edited after that point; a fix belongs in a new V003,
-- not here.
--
-- Outbox Pattern: `outbox` is written to in the SAME transaction as
-- connection_requests.status flipping to ACCEPTED (see
-- ConnectionServiceImpl.acceptConnection / OutboxServiceImpl.publish) — the
-- DB transaction's atomicity is what guarantees the status change and this
-- table's row either both commit or neither does. A separate, later
-- process (the relay, explicitly out of scope for T030) polls this table
-- for PENDING rows and hands them to Kafka.
CREATE TABLE outbox (
    id          BIGINT IDENTITY(1,1) PRIMARY KEY,

    topic       NVARCHAR(255)   NOT NULL,

    -- NVARCHAR(MAX): payload is an opaque, already-serialized JSON string
    -- (see OutboxEvent's own comment) — this table never needs to query
    -- into individual fields of it, so there is no reason to model its
    -- structure in DDL.
    payload     NVARCHAR(MAX)   NOT NULL,

    -- Same Open/Closed reasoning as connection_requests.status in V001:
    -- plain NVARCHAR, not a CHECK constraint, so a future OutboxStatus
    -- value (e.g. DLQ, per the kafka-outbox skill) is a code change, not a
    -- schema migration.
    status      NVARCHAR(20)    NOT NULL DEFAULT 'PENDING',

    created_at  DATETIME2       NOT NULL DEFAULT SYSUTCDATETIME()
);

-- The future relay's entire query shape is "give me PENDING rows, oldest
-- first" — indexed on status now so that query can seek instead of scan
-- from the moment the relay ships, instead of retrofitting this index onto
-- a table that has already accumulated rows.
CREATE INDEX idx_outbox_status ON outbox (status);

-- Saga (Choreography): saga_state is Connection Service's own paper trail
-- for ConnectionLifecycleSaga, from this service's point of view only — see
-- SagaState.java's class comment for why saga_id is BIGINT here (not the
-- UNIQUEIDENTIFIER the saga.md skill's generic example shows) and why no
-- @GeneratedValue applies to it.
CREATE TABLE saga_state (
    -- No IDENTITY: this id IS the connection's own id (connection_requests.id),
    -- assigned by the calling code, not generated by this table.
    saga_id       BIGINT          PRIMARY KEY,

    saga_type     VARCHAR(64)     NOT NULL,
    current_step  VARCHAR(64)     NOT NULL,
    status        VARCHAR(32)     NOT NULL,
    context       NVARCHAR(MAX)   NULL,
    started_at    DATETIME2       NOT NULL,
    updated_at    DATETIME2       NOT NULL
);

-- No extra index beyond the primary key: with only one write path
-- (acceptConnection upserting by saga_id) and no query pattern yet beyond
-- "look up this exact saga by its id", the clustered PK index already
-- covers every access this ticket needs. A future saga-timeout job (per
-- saga.md's detectStuckSagas example) would justify an index on
-- (current_step, status, updated_at) — deferred until that job actually
-- exists.
